modLoader="javafml"
loaderVersion="[47,)"
license="Assets fall under ARR, code falls under MIT"

[[mods]]
modId="factory_expansion"
version="1.20.1-0.0.1"
displayName='Factory Expansion'
displayUrl='https://github.com/TeamCitrusMods/Factory-Expansion'
authors="ElysiaSilly, GraeyAmber, VertexCubed"
description='''
The Factory Needs To Grow- Erm, Expand!

Factory Expansion is an industrial-style decoration mod which focuses on adding stylish blocks to enhance your factory layout.

We are not responsible, nor do we take responsibility and liability for any accidents caused by build code violations, safety hazards, and unregulated substances/chemicals.
'''

[[dependencies.thermal_fne]]
    modId="forge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.thermal_fne]]
    modId="minecraft"
    mandatory=true
    versionRange="${mc_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.thermal_fne]]
modId = "cofh_core"
mandatory = false
versionRange = "${cofh_core_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_fne]]
modId = "thermal"
mandatory = false
versionRange = "${thermal_core_version_range}"
ordering = "AFTER"
side = "BOTH"
