modLoader="javafml"
loaderVersion="[43,)"
license="Assets fall under ARR, code falls under MIT"

[[mods]]
modId="factory_expansion"
version="1.19.2-0.0.1"
displayName='Thermal: Factory Needs Expansion'
displayUrl='https://github.com/TeamCitrusMods/Factory-Expansion'
logoFile = "logo.png"
credits='Team CoFH, Team Citrus'
authors="ElysiaSilly, GraeyAmber"
description='''
Thermal: The Factory Needs To Grow- Erm, Expand!

Thermal: Factory Needs Expansion is an addon for Team CoFH's Thermal Suite mods, with a focus on expanding various deco and building options for all your industrial needs.

We are not responsible, nor do we take responsibility and liability for any accidents caused by build code violations, safety hazards, and unregulated substances/chemicals.
'''

[[dependencies.factory_expansion]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.factory_expansion]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.factory_expansion]]
modId = "cofh_core"
mandatory = true
versionRange = "[${cofh_core_version}, ${cofh_core_max_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.factory_expansion]]
modId = "thermal"
mandatory = true
versionRange = "[${thermal_core_version}, ${thermal_core_max_version}]"
ordering = "AFTER"
side = "BOTH"
